// ─── Enums ────────────────────────────────────────────────────────────────────

export type TaskStatus   = 'NEW' | 'ASSIGNED' | 'IN_PROGRESS' | 'REVIEW' | 'DONE' | 'CANCELLED';
export type TaskPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
export type TaskType     =
  | 'ORDER_PREPARATION'
  | 'RETURN_PROCESSING'
  | 'PRICE_UPDATE'
  | 'PROMOTION_SETUP'
  | 'MEETING'
  | 'INVENTORY_CHECK'
  | 'OTHER';
export type TaskSourceType = 'ORDER' | 'RETURN' | 'PRICE_CHANGE' | 'PROMOTION' | 'MANUAL';
export type TaskActivityAction =
  | 'CREATED' | 'STATUS_CHANGED' | 'ASSIGNEE_CHANGED' | 'TITLE_UPDATED'
  | 'PRIORITY_CHANGED' | 'DUE_DATE_CHANGED' | 'COMMENTED' | 'ATTACHMENT_ADDED'
  | 'CHECKLIST_UPDATED' | 'LABEL_CHANGED' | 'PARTICIPANT_ADDED' | 'PARTICIPANT_REMOVED' | 'DELETED';

// ─── Entities ─────────────────────────────────────────────────────────────────

export interface AssigneeInfo {
  id: number;
  username: string;
  fullName: string | null;
  avatar: string | null;
}

export interface ChecklistSummary {
  total: number;
  done: number;
  percentage: number;
}

export interface TaskResponse {
  id: number;
  boardId: number;
  status: TaskStatus;
  priority: TaskPriority;
  taskType: TaskType;
  departmentId: number | null;
  title: string;
  description: string | null;
  creator: AssigneeInfo | null;
  assignee: AssigneeInfo | null;
  dueDate: string | null;
  startedAt: string | null;
  completedAt: string | null;
  position: number;
  sourceType: TaskSourceType | null;
  sourceId: number | null;
  isAutoGenerated: boolean;
  createdDate: string;
  modifiedDate: string;
  checklistSummary: ChecklistSummary | null;
  commentCount: number;
  attachmentCount: number;
}

export interface TaskCommentResponse {
  id: number;
  taskId: number;
  author: AssigneeInfo;
  parentId: number | null;
  content: string;
  isEdited: boolean;
  editedAt: string | null;
  createdDate: string;
}

export interface TaskActivityLogResponse {
  id: number;
  actor: AssigneeInfo | null;
  actionType: TaskActivityAction;
  oldValue: Record<string, unknown> | null;
  newValue: Record<string, unknown> | null;
  createdAt: string;
}

export interface TaskAttachmentResponse {
  id: number;
  taskId: number | null;
  commentId: number | null;
  uploader: AssigneeInfo | null;
  fileName: string;
  filePath: string;
  fileSize: number | null;
  mimeType: string | null;
  createdAt: string;
}

export interface TaskNotificationResponse {
  id: number;
  taskId: number | null;
  taskTitle: string | null;
  notificationType: string;
  title: string;
  body: string | null;
  isRead: boolean;
  readAt: string | null;
  createdAt: string;
}

export interface DashboardStats {
  total: number;
  inProgress: number;
  review: number;
  overdue: number;
  completedToday: number;
}

export interface KanbanBoardResponse {
  boardId: number;
  boardName: string;
  columns: Record<TaskStatus, TaskResponse[]>;
  stats: DashboardStats;
}

// ─── Requests ─────────────────────────────────────────────────────────────────

export interface CreateTaskRequest {
  boardId: number;
  title: string;
  description?: string;
  taskType: TaskType;
  departmentId?: number | null;
  priority: TaskPriority;
  assigneeId?: number;
  dueDate?: string;
  participantIds?: number[];
}

export interface UpdateTaskRequest {
  title?: string;
  description?: string;
  taskType?: TaskType;
  departmentId?: number | null;
  priority?: TaskPriority;
  assigneeId?: number;
  dueDate?: string;
}

export interface MoveTaskRequest {
  targetStatus: TaskStatus;
  targetPosition: number;
  note?: string;
}

export interface AddCommentRequest {
  content: string;
  parentId?: number;
}

export interface AddChecklistRequest {
  title: string;
  items?: string[];
}
